version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PRISMA_DATABASE_CONNECTION_URL: "mysql://${DATABASE_CONTAINER_USERNAME}:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}"
    command: /app/docker/entrypoint.sh

  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_CONTAINER_USERNAME: ${DATABASE_CONTAINER_USERNAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 3
