services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/node_app/app
      - ./prisma:/node_app/prisma
      - ./server:/node_app/server
      - ./public:/node_app/public
      - ./database:/node_app/database
      - ./docker/entrypoint.sh:/node_app/docker/entrypoint.sh
      - ./nuxt.config.ts:/node_app/nuxt.config.ts
      - ./tsconfig.json:/node_app/tsconfig.json
      - ./sentry.client.config.ts:/node_app/sentry.client.config.ts
      - ./sentry.server.config.ts:/node_app/sentry.server.config.ts
      - ./package.json:/node_app/package.json
      - ./package-lock.json:/node_app/package-lock.json
      - type: volume
        source: node-modules
        target: /node_app/node_modules
      - type: volume
        source: nuxt
        target: /node_app/.nuxt
    depends_on:
      db:
        condition: service_healthy
    environment:
      PRISMA_DATABASE_CONNECTION_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}"
      APP_PORT: ${APP_PORT}
      DB_PORT: ${DB_PORT}
    working_dir: /node_app
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate dev && npx prisma generate && npm run dev"

  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 15s
      timeout: 10s
      retries: 3

volumes:
  node-modules:
  nuxt:
