version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    

  db:
    image: mariadb:10.11
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 10s
      retries: 3

  prisma:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PRISMA_DATABASE_CONNECTION_URL: ${PRISMA_DATABASE_CONNECTION_URL}
